execute_process(COMMAND "${EXTRACTED}" --snapshot extracted.bin RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Extracted library tests failed: ${result}")
endif()
execute_process(COMMAND "${REFERENCE}" --snapshot reference.bin RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Upstream library tests failed: ${result}")
endif()
file(SHA256 extracted.bin actual)
file(SHA256 reference.bin expected)
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Upstream parity mismatch: ${actual} != ${expected}")
endif()
message(STATUS "CPU output matches upstream: ${actual}")
