name: Portable libdds

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cpu-library:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, windows-11-arm, ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build/libdds -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build/libdds --config Release --parallel
      - name: Test
        run: ctest --test-dir build/libdds -C Release --output-on-failure

  sanitizers:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: >-
          cmake -S . -B build/libdds
          -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer"
      - name: Build
        run: cmake --build build/libdds --parallel
      - name: Test
        env:
          UBSAN_OPTIONS: halt_on_error=1
          ASAN_OPTIONS: detect_leaks=1
        run: ctest --test-dir build/libdds --output-on-failure
